$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: prepare_score
display_name: Data Preparation for Scoring
version: 1
type: command
inputs:
  input_data:
    type: uri_folder
outputs:
  output_data:
    type: uri_folder

    
code: ../scripts

environment: azureml://registries/azureml/environments/sklearn-1.0/versions/18

command: >-
  python prepare_score.py 
  --input_data ${{inputs.input_data}}
  --output_data ${{outputs.output_data}}
