$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: score_model
display_name: Score
version: 1
type: command

inputs:
  input_data: 
    type: uri_folder
  input_model:
    type: mlflow_model
outputs:
  output_data:
    type: uri_folder

 
code: ../scripts
environment: azureml://registries/azureml/environments/sklearn-1.0/versions/18
command: >-
  python score_model.py
  --input_data ${{inputs.input_data}}
  --input_model ${{inputs.input_model}}
  --output_data ${{outputs.output_data}}
